---
- name: Force systemd to reread configs
  systemd: daemon_reload=yes
  when: ansible_service_mgr == "systemd"

- name: Restart yarn-nodemanager
  service: name=yarn-nodemanager state=restarted
  when:
   - inventory_hostname in hdfs_namenodes[0]
   - hdfs_ansible_handlers|bool

- name: Restart yarn-resourcemanager
  service: name=yarn-resourcemanager state=restarted
  when:
   - inventory_hostname in hdfs_namenodes[0]
   - hdfs_ansible_handlers|bool

- name: Restart namenode
  service: name=hdfs-namenode state=restarted
  when:
   - inventory_hostname in hdfs_namenodes[0]
   - hdfs_ansible_handlers|bool

- name: Restart datanode
  service: name=hdfs-datanode state=restarted
  when:
   - inventory_hostname in hdfs_datanodes
   - hdfs_ansible_handlers|bool

- name: Restart journalnode
  service: name=hdfs-journalnode state=restarted
  when:
   - hdfs_ha_enabled
   - inventory_hostname in hdfs_journalnodes
   - hdfs_ansible_handlers|bool

- name: Restart zkfc
  service: name=hdfs-zkfc state=restarted
  when:
   - hdfs_ha_enabled
   - inventory_hostname in hdfs_namenodes
   - hdfs_ansible_handlers|bool

- name: Restart secondary namenode
  service: name=hdfs-secondarynamenode state=restarted
  when:
   - not hdfs_ha_enabled
   - inventory_hostname in hdfs_secondary_namenode
   - hdfs_ansible_handlers|bool
